### ISSUE TITLE
Is the project still under development

### ISSUE THREAD

**Issue by appetrosyan** [yi-editor/yi#1114]
Hi, THe project didn't seem to get any updates in over a year, and I was wondering if the project was dead...

**Comment by noughtmare** [comment]
The last real maintainer @ethercrow 'retired' about two years ago. Since then, I have tried to take over some parts of maintenance, but I have not been able to sustain that due to being very busy with my university studies.

I also feel that the current implementation uses outdated design techniques (e.g. transformers without mtl-style type classes) and I feel like the code has become a mess. I have tried to explore another point in the design space with [Jak](https://github.com/noughtmare/jak), but that hasn't reached a usable state. Another related project is [rasa](https://github.com/ChrisPenner/rasa), but that is also not very actively developed anymore.

I would say that Yi is indeed dead and I have heard of no plans to revive it.

**Comment by xnox** [comment]
yi is now removed from Ubuntu, as it fails to build from source with 8.8.3 based ghc stack & dependencies.

**Comment by jorsn** [comment]
A hint in the readme would be nice.

**Comment by noughtmare** [comment]
I've added a short notice at the top of the readme.

**Comment by noughtmare** [comment]
There has been a development: @vivid-synth has stepped in to at least minimally maintain Yi such that it can remain as a Debian package.

**Comment by appetrosyan** [comment]
@vivid-synth Thank you very much for stepping in!

**Comment by zateal** [comment]
**Can I sponsor a Yi project using USDT for example?**

**Comment by zateal** [comment]
> **Can I sponsor a Yi project using USDT for example?**

Who knows, maybe if from the very beginning everyone could sponsor this project, it would not have ended this way: D

**Comment by zateal** [comment]
![rect859.png](https://imageshost.ru/images/2021/04/22/rect859.png)

Green lines indicate stable degradation.
Red - about the possible end of degradation and the beginning of development.

For development to happen, need to somehow provoke an impulse.

**Comment by zateal** [comment]
This is for motivation)

**Comment by mfourne** [comment]
I'd like to get involved and take over some of the maintenance burden (see #1125 ), as I have been doing for the related packages in Debian for some time. I can't guarantee timely and new development on my own, but I would be sad to see this project vanish. I don't know who feels responsible and has the access rights, but please read this as my request to join the project. :)

**Comment by mhatta** [comment]
@mfourne I'm also a Debian developer and a member of debian-haskell group (actually, I once made some fixes for yi-related debs a while ago).  I'm willing to help.

**Comment by spaette** [comment]
_cf_: https://github.com/yi-editor/yi/issues/1114#issuecomment-1218094590

@noughtmare 

What do you think about inviting @mfourne to be a Member of the yi-editor Organization?

<hr>

Another functional coding [project](https://wryun.github.io/es-shell/); unfortunately Frederic Koehler's C++ version, _i.e._ xs, became abandonware last year.

xs builds with meson-0.54.x or meson-0.56.x

**Comment by spaette** [comment]
@Fuuzetsu

> What do you think about inviting @mfourne to be a Member of the yi-editor Organization?

**Comment by Fuuzetsu** [comment]
I sent mfourne an invite for maintainer role and also added to Hackage maintainers.

To answer the question in the OP: no, I don't think this project is under development, as in: no one is working on it. I'll close the ticket.
