### ISSUE TITLE
Feedback requested: what would be the impact of deleting `System.PosixCompat.User` from `unix-compat`?

### ISSUE THREAD

**Issue by mitchellwrosen** [yi-editor/yi#1133]
Hi there,

I've recently taken over maintainership of `unix-compat`, and I intend to push out a `unix-2.8`-compatible release as soon as I can. One remaining issue is what to make of the `System.PosixCompat.User` module, as the `UserEntry` type has changed.

Here is the first PR that attempts to graft over the differences: https://github.com/jacobstanley/unix-compat/pull/60/files

And here is my preferred solution, to delete the `System.PosixCompat.User` module entirely, based on the observation that `System.PosixCompat.User` doesn't seem useful at all, as all functions either return dummy data or throw exceptions: https://github.com/jacobstanley/unix-compat/pull/62

However, I see that `yi-core` actually use this module. Could you please consider the effect of deleting `System.PosixCompat.User` on the `stack` codebase, and let me know if that is a reasonable option, or if you'd rather see a different approach to `unix-2.8` support?

Thanks.

**Comment by mfourne** [comment]
Thank you for reaching out to us! I will look at this on the weekend, time permitting, since I don't currently know how that code interacts with the other parts in the codebase. Personally, I'd be fine getting rid of it, but I don't want to commit to that too hastily.

**Comment by mfourne** [comment]
I have pulled out usage of System.PosixCompat.User and now we're failing ourselves directly for mingw32_HOST_OS, just like unix-compat did before anyway. 
I can't currently upload a new version of yi-core to hackage due to only being maintainer for some of the yi packages (namely just: yi), but I have asked some other developer to give me access to make everything on hackage build with unix-compat-0.7. This issue should be open until I can do that upload.

**Comment by mfourne** [comment]
Uploaded new yi-core to hackage as well.
