### ISSUE TITLE
Extra torture to install on OSX

### ISSUE THREAD

**Issue by gitfoxi** [yi-editor/yi#768]
Using homebrew:

```
brew install icu4c
cabal install text-icu --extra-lib-dirs=/usr/local/opt/icu4c/lib/ --extra-include-dirs=/usr/local/opt/icu4c/include
```

**Comment by Fuuzetsu** [comment]
Yes, because cabal is not a system package manager. This is nothing we can do about and if anything, the installation instructions need to go to `text-icu` package, not us. If you want to send a PR adding a note to the installation instructions somewhere then I'd probably take it but I'm closing this as invalid.
