### ISSUE TITLE
sample configurations for vim do not load nicely on ubuntu 14.04

### ISSUE THREAD

**Issue by aniketd** [yi-editor/yi#782]
Under `tmux -2` ...

![foryiissue](https://cloud.githubusercontent.com/assets/922486/10815241/c94ada42-7e50-11e5-8e28-610d941bacab.png)

**Comment by siddhanathan** [comment]
Can you also show the config file you're using?

**Comment by anicake** [comment]
{-# LANGUAGE OverloadedStrings #-}

import           Data.Monoid
import           Yi hiding (super)
import qualified Yi.Keymap.Vim as V2
import qualified Yi.Keymap.Vim.Common as V2
import qualified Yi.Keymap.Vim.Utils as V2
import qualified Yi.Mode.Haskell as Haskell
import qualified Yi.Rope as R

main :: IO ()
main = yi $ defaultVimConfig {
    modeTable = myModes ++ modeTable defaultVimConfig,
    defaultKm = myKeymapSet,
    configCheckExternalChangesObsessively = False
}

myKeymapSet :: KeymapSet
myKeymapSet = V2.mkKeymapSet $ V2.defVimConfig `override` \super this ->
    let eval = V2.pureEval this
    in super {
          -- Here we can add custom bindings.
          -- See Yi.Keymap.Vim.Common for datatypes and
          -- Yi.Keymap.Vim.Utils for useful functions like mkStringBindingE

          -- In case of conflict, that is if there exist multiple bindings
          -- whose prereq function returns WholeMatch,
          -- the first such binding is used.
          -- So it's important to have custom bindings first.
          V2.vimBindings = myBindings eval <> V2.vimBindings super
        }

myBindings :: (V2.EventString -> EditorM ()) -> [V2.VimBinding]
myBindings eval =
    let nmap x y = V2.mkStringBindingE V2.Normal V2.Drop (x, y, id)
        imap x y = V2.VimBindingE (\evs state -> case V2.vsMode state of
                                    V2.Insert _ ->
                                        fmap (const (y >> return V2.Continue))
                                             (evs `V2.matchesString` x)
                                    _ -> V2.NoMatch)
    in [ nmap "<C-h>" previousTabE
       , nmap "<C-l>" nextTabE

         -- Press space to clear incremental search highlight
       , nmap " " (eval ":nohlsearch<CR>")

         -- for times when you don't press shift hard enough
       , nmap ";" (eval ":")

       , nmap "<F3>" (withCurrentBuffer deleteTrailingSpaceB)
       , nmap "<F4>" (withCurrentBuffer moveToSol)
       , nmap "<F1>" (withCurrentBuffer readCurrentWordB >>= printMsg . R.toText)
       , imap "<Home>" (withCurrentBuffer moveToSol)
       , imap "<End>" (withCurrentBuffer moveToEol)
       ]

myModes :: [AnyMode]
myModes = [
         AnyMode Haskell.fastMode {
             -- Disable beautification
             modePrettify = const $ return ()
         }
    ]

**Comment by siddhanathan** [comment]
It seems to work for me. My guess is you may be using a sandbox? If that's the case, try this:

```bash
$ cabal update
$ cabal install --global yi
```

That should install yi 0.12.2

Let me know if that works.

**Comment by anicake** [comment]
I used `stack install yi` to install it. Would that have put it in a sandbox?

**Comment by siddhanathan** [comment]
Thanks for bringing this issue up.

cabal by default should find yi, unless you changed the cabal database to use stackage instead.

Yes, stack is sandboxing. Seems like stack is using it's own version of GHC. Since yi spawns its own instance of GHC via Dyre, this is causing an issue.

This could probably use a compiler flag. I know @Fuuzetsu fixed this issue for nix, but maybe we should allow compiler flags which allow any version of ghc with any package database.

I'm not sure what the right fix is, but I can give a temporary workaround.

The stack.yaml file can be as simple as:

```yaml
flags:
  yi:
    pango: false
    eventlog: false
    vty: true
    hint: true
    testing: true
    profiling: false
extra-package-dbs: []
packages:
- '.'
extra-deps: []
resolver: nightly-2015-11-04
```

Simply use the following:

```bash
$ # grab the source code
$ cd yi
$ # copy the stack.yaml file over
$ stack install yi
$ stack exec yi --package yi
```

`stack exec` should be used inside the yi directory if you want to grab the correct ghc packages. The command `stack exec yi --package yi` tells stack to execute the yi binary, but depend on all yi packages while doing so. Definitely not the best thing to do, but I'm not an expert with stack. I'm sure there must be some option in the stack.yaml file which controls the package database accessible to yi.

Once we figure out a decent solution with stack, this should definitely go in the [documentation](http://yi-editor.github.io/pages/installing/).

**Comment by anicake** [comment]
what you suggested worked. Now I need to learn how to use this editor. :)

**Comment by noughtmare** [comment]
Can this be closed @siddhanathan @aniketd?

**Comment by siddhanathan** [comment]
@noughtmare Yes. Please close this issue. Will update the documentation to make instructions clearer soon.
