### ISSUE TITLE
Use microlens instead of lens.

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#819]
I don't know if it is possible, maybe @neongreen can help us with that.

I have started on this in [my branch](https://github.com/noughtmare/yi/tree/microlens), but I get this error:
```
    src/library/Yi/Buffer/Misc.hs:1111:70-90:
        Couldn't match type ‘m’ with ‘BufferM’
          ‘m’ is a rigid type variable bound by
              the type signature for
                getBufferDyn :: (Default a, YiVariable a, MonadState FBuffer m,
                                 Functor m) =>
                                m a
              at src/library/Yi/Buffer/Misc.hs:1110:24
        Expected type: Data.DynamicState.Serializable.DynamicState -> m ()
          Actual type: Data.DynamicState.Serializable.DynamicState
                       -> BufferM ()
        Relevant bindings include
          getBufferDyn :: m a (bound at src/library/Yi/Buffer/Misc.hs:1111:1)
        In the second argument of ‘getDyn’, namely
          ‘(assign bufferDynamicA)’
        In the second argument of ‘(<$>)’, namely
          ‘getDyn (use bufferDynamicA) (assign bufferDynamicA)’
    
    src/library/Yi/Buffer/Misc.hs:1118:45-65:
        Couldn't match type ‘m’ with ‘BufferM’
          ‘m’ is a rigid type variable bound by
              the type signature for
                putBufferDyn :: (YiVariable a, MonadState FBuffer m, Functor m) =>
                                a -> m ()
              at src/library/Yi/Buffer/Misc.hs:1117:17
        Expected type: Data.DynamicState.Serializable.DynamicState -> m ()
          Actual type: Data.DynamicState.Serializable.DynamicState
                       -> BufferM ()
        Relevant bindings include
          putBufferDyn :: a -> m ()
            (bound at src/library/Yi/Buffer/Misc.hs:1118:1)
        In the second argument of ‘putDyn’, namely
          ‘(assign bufferDynamicA)’
        In the expression:
          putDyn (use bufferDynamicA) (assign bufferDynamicA)
```

**Comment by neongreen** [comment]
It's possible that you've been bitten by the monomorphism restriction when you wrote `assign = (.=)` without a type signature. Try copying the signature from the definition of `.=`.

Also, could you open an issue on the microlens bug tracker about adding assign? 

Also, if you use microlens-platform instead of other microlens packages, you'll have less imports. 

Also, your cabal file seems to mention microlens-th twice.

**Comment by noughtmare** [comment]
Thank you!
Also I have opened the issue.
Also also, I am changing it right now.
Also also also, I must have accidentally pressed 'p' in vim.

**Comment by neongreen** [comment]
Thanks! 

I'm not sure I'll add `uses`, since it's just `f <$> use l`. I think I will add `<&>`, tho, since it's useful for writing lenses.

Currently I'm at a place with very bad internet. I'll try to make the commits anyway since I really really don't want to break the commit streak, but no promises. I'll be home by July 4th, tho.

**Comment by jhance** [comment]
Since yi is an application not a library why do we want to use microlens?

**Comment by ethercrow** [comment]
I see yi as a library and user's config as an application. Also shaving an extra minute from build times is always nice.

If we find a place in yi that will greatly benefit from depending on lens, we'll switch back.

**Comment by jhance** [comment]
My concerns are more about things like https://github.com/yi-editor/yi-language/blob/master/src/Yi/Regex.hs, if we find ourselves re-implementing things like this it will become a strong codesmell (and also having our own version of typeclasses that otherwise exist elsewhere is clearly bad for compatibility)
