### ISSUE TITLE
Keybindings to `(eval ":w<CR>")` don't work

### ISSUE THREAD

**Issue by atondwal** [yi-editor/yi#910]
When I replace `:nohlsearch` with `:w` in ethercrow/yi-config, and try to use the keybinding, I get:

`Not an editor command: w`

(The same is true of `:write`)

**Comment by noughtmare** [comment]
Whar version of yi are you using? Does ethercrow's config work without the modification?

**Comment by atondwal** [comment]
I'm using the current master (` 51855c9`). The config works perfectly as written without this change.

**Comment by noughtmare** [comment]
I think the issue is that nmap only evaluates pure commands (e.g. `:nohl<CR>` or `:11<CR>`), but `:w<CR>` is an impure command.

A workaround:

1. on line 55 change `let eval = V.pureEval this` to `let eval es = V.impureEval this es False`
2. on line 64 change `EditorM ()` to `YiM ()`
3. on line 76 change `nmap " " (eval ":nohlsearch<CR>")` to `nmapY " " (eval ":w<CR>")`
4. on line 77 change `nmap` to `nmapY`

**Comment by noughtmare** [comment]
I don't know what the preferred way to bind impure eval commands is, @ethercrow probably knows more about this.

**Comment by atondwal** [comment]
Oh, I didn't realize `eval` is defined locally in the config file... I should've read the whole thing. Thanks!
