### ISSUE TITLE
Can't install yi with pango frontend

### ISSUE THREAD

**Issue by RyanGlScott** [yi-editor/yi#917]
I'm trying to install yi with the `pango` frontend enabled. However, when I try following the instructions in the [documentation](http://yi-editor.github.io/pages/installing/), things go awry:

```
$ cabal install yi -fpango --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
yi-language-0.13.0.2
yi-core-0.13.0.2
yi-frontend-vty-0.13.0.2
yi-misc-modes-0.13.0.2
yi-keymap-emacs-0.13.0.2
yi-mode-haskell-0.13.0.2
yi-mode-javascript-0.13.0.2
yi-0.13.0.2
```

Notice that `yi-frontend-pango` never actually gets installed, even if I specify it manually! And sure enough:

```
$ yi --frontend=pango
yi: Panic: frontend not found
```

**Comment by zanzix** [comment]
If it's the same error that I had, you need to replace the default config in "~/.config/yi/yi.hs" with one of the configs from the "example-configs" directory in the yi source folder.

**Comment by RyanGlScott** [comment]
That's nice, but unfortunately I'm trying to install `yi` on Windows, and the `pango` backend is the _only_ one that can work on Windows. So I'm in a position where I don't have the ability to edit `~/.config/yi/yi.hs`, since I can't install `yi` in the first place.

**Comment by zanzix** [comment]
I'm confused, in your first post you said you have installed to without the
front-end, and now you say you can't installing it at all?

**Comment by zanzix** [comment]
"install Yi without front-end", silly autocorrect

**Comment by RyanGlScott** [comment]
The fact that I can't install it with the `pango` plugin implies that I can't install it on Windows. The only other frontend is `vty`, which requires `unix` (which won't install on Windows for obvious reasons).

**Comment by zanzix** [comment]
Ugh no. You have jumped to some conclusions right there.

**Comment by RyanGlScott** [comment]
...do you mind giving an explanation?

**Comment by zanzix** [comment]
Yup, sure. 

So you run yi with the pango flag:
` yi --frontend=pango

And it responds with:
`yi: Panic: frontend not found
`
The first thing you need to observe is that *yi responded to you*. Therefore yi has been installed. 

Your mistake was to assume that it's a *fact* that yi has not installed the pango plugin. But if that was the case, then it would have complained during installation. Instead, what's happened is that yi can not *find* the pango plugin.

The reason that Yi can not find the plugin is because AFAIK there was a breaking change in yi 0.13 (which just came out) - the frontend needs to be specified in the config of yi. 
Your yi installation is launching the default config (which does not have a frontend specified) and is giving you the error.
 `yi: Panic: frontend not found
That line, "Panic: frontend not found" is a line taken *from the default config file*. That's how I know that your yi is installed correctly. 

Which brings us back to your first assumption:

> That's nice, but unfortunately I'm trying to install yi on Windows, and the pango backend is the only one that can work on Windows. So I'm in a position where I don't have the ability to edit ~/.config/yi/yi.hs, since I can't install yi in the first place.

You don't need to use Yi to modify the yi config, it's just an .Hs file. You can use any other editor for that (or just copy paste the file). You will need the file from either emacs-dynamic or vim-dynamic folders depending on which other editor you prefer.
Since you're on Windows your config file won't be in "~/.config/yi/yi.hs" but in a Windows equivalent. (Probably in the same folder that you're running yi from?) My guess is just to use the search function, or maybe run the windows program for searching within text files and search for files containing the text 'Panic: frontend not found'. 

In case you've already seen the example configs and noticed that all of them are for Vty, that is easily fixed: simply replace Yi.Config.Default.Vty (configureVty) with import   Yi.Config.Default.Pango (configurePango). 

All of this, really, should have been documented (and I spent a few hours recently figuring this out myself after I upgraded). So uh, I hope this does not discourage you from hacking on yi. 

Let me know if you have any further questions - I'm kind of planning to write up an unofficial documentation for yi to help people with these sort of things.

**Comment by RyanGlScott** [comment]
Sorry, I think I might not have clear enough. I discovered this bug originally on a Linux box, which is why I was able to type `yi --frontend=pango` in the first place. I tried installing `yi` on Windows separately. So you're right - I could certainly workaround this issue on Linux, but on Windows I'm in trouble, because I can't "bootstrap" `yi` so to speak.

**Comment by zanzix** [comment]
Oh, the switch between OSs did confuse me as you did not mention Windows in the original post. 

I'm not even sure which ones of your outputs are then from Windows and which ones from Linux, or what even the Windows problem is.

**Comment by RyanGlScott** [comment]
The output of `yi --frontend=pango` was from Linux. As I said above, the problem on Windows is that due to this bug, the only backend `yi` allows you to install at the moment is the `vty` one. But `vty` depends on the `unix` package which, as the name implies, contains lots of Unix-specific functionality and thus cannot be installed on Windows. As a consequence, you effectively cannot install `yi` on Windows at the moment, as there isn't a way to pick the `pango` backend when installing it.

**Comment by zanzix** [comment]
I do not understand why - if your problem is with windows- you are giving
the Linux output?

What you've shown so far from your Linux output - as I've said above - *is
not a bug*. Your frontend is installed. It's just *not configured*.

I cannot offer any advice for your problem with Windows as you are *not
showing me the problem* (ie the output that you get from your failed
windows installation).

Linux and windows installations work quite differently and the bugs are not
isomorphic.

**Comment by RyanGlScott** [comment]
If you want the exact error message you get when installing the `unix` dependency on Windows, here you go:

```
$ cabal install yi -fpango --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
charsetdetect-ae-1.1.0.1
terminfo-0.4.0.2
unix-2.7.2.0
vty-5.11
yi-rope-0.7.0.2
yi-core-0.13.0.2
yi-frontend-vty-0.13.0.2
yi-misc-modes-0.13.0.2
yi-keymap-emacs-0.13.0.2
yi-mode-haskell-0.13.0.2
yi-mode-javascript-0.13.0.2
yi-0.13.0.2

$ cabal install yi -fpango -j1
<lots of build output elided>
Resolving dependencies...
Downloading unix-2.7.2.0...
cabal: Entering directory 'C:\msys64\tmp\cabal-tmp-5012\unix-2.7.2.0'
Configuring unix-2.7.2.0...
cabal.exe: No executables, libraries, tests, or benchmarks found. Nothing to
do.
cabal: Leaving directory 'C:\msys64\tmp\cabal-tmp-5012\unix-2.7.2.0'
Failed to install unix-2.7.2.0
cabal.exe: Error: some packages failed to install:
unix-2.7.2.0 failed during the configure step. The exception was:
ExitFailure 1
```

**Comment by zanzix** [comment]
Thanks for the output.

That is very strange indeed. 

I wish I could help but my knowledge of Windows is lacking. 

Perhaps someone else knows more?

**Comment by RyanGlScott** [comment]
I have a hunch what the issue is. For one thing, the `-fpango` flag advertised in [the documentation](http://yi-editor.github.io/pages/installing/) does not actually do anything ever since the `yi-0.13.0.0` release, to the best of my knowledge. ([`-fpango` was a thing as of `yi-0.12.6`, however](http://hackage.haskell.org/package/yi-0.12.6/yi.cabal)).

The issue goes deeper than that, however. In `Yi.Core.Default` in `yi-0.12.6`, there [used to be code](http://hackage.haskell.org/package/yi-0.12.6/docs/src/Yi-Config-Default.html) like so:

```haskell

availableFrontends :: [(String, UIBoot)]
availableFrontends =
#ifdef FRONTEND_VTY
   ("vty", Yi.UI.Vty.start) :
#endif
#ifdef FRONTEND_PANGO
   ("pango", Yi.UI.Pango.start) :
#endif
  [("batch", Yi.UI.Batch.start)]

defaultConfig :: Config
defaultConfig =
  publishedActions .~ defaultPublishedActions $
  Config { startFrontEnd    = case availableFrontends of
             [] -> error "panic: no frontend compiled in! (configure with -fvty or another frontend.)"
             ((_,f):_) -> f
         , ...
         }
```

But in the [current version](https://github.com/yi-editor/yi/blob/8fe18c77d26af9c56d2ffbc1e1a7911ae7321983/yi-core/src/Yi/Config/Default.hs) of `yi-core` (where `Yi.Config.Default` now lives), `availableFrontends` no longer exists, and `defaultConfig`'s definition is quite different:

```haskell
defaultConfig :: Config
defaultConfig =
  publishedActions .~ defaultPublishedActions $
  Config { startFrontEnd    = error "panic: no frontend compiled in! (configure with -fvty or another frontend.)"
         , ...
         }
```

Now, there doesn't seem to be any kind of choice between the frontends at all. And [the `yi` executable's code](https://github.com/yi-editor/yi/blob/8fe18c77d26af9c56d2ffbc1e1a7911ae7321983/yi/src/Main.hs) doesn't give any indication that the `pango` frontend is choosable either:

```haskell
main :: IO ()
main = do
    cfg <- execStateT configure defaultConfig
    yiDriver' True cfg
    where
    configure = runConfigM $ do
        configureVty
        configureEmacs
        configureHaskellMode
        configureJavaScriptMode
        configureMiscModes
```

All signs point to the `vty` frontend only. More evidence is in [`yi`'s `package.yaml`](https://github.com/yi-editor/yi/blob/8fe18c77d26af9c56d2ffbc1e1a7911ae7321983/yi/package.yaml):

```yaml
dependencies:
    - base >= 4.8 && < 5
    - mtl >= 2.2
    - yi-core >= 0.13
    - yi-frontend-vty >= 0.13
    - yi-keymap-emacs >= 0.13
    - yi-mode-haskell >= 0.13
    - yi-mode-javascript >= 0.13
    - yi-misc-modes >= 0.13
```

Again, it only mentions `yi-frontend-vty`, not `yi-frontend-pango`.

Is there some way to bring the `pango` frontend support back to the way it was before `yi-0.13`?

**Comment by zanzix** [comment]
Erm, I did tell you in my long post that you have to replace

configureVty 

with 

configurePango 


 . . .

**Comment by RyanGlScott** [comment]
Sure, but again, I can't install `yi` on Windows, period. So I can't obtain a local `~/.config/yi/yi.hs` that I can edit in the first place, which is the whole reason I'm submitting this bug report. Something needs to be fixed upstream.

**Comment by zanzix** [comment]
What happens if you install yi on windows without any frontend flags?

**Comment by RyanGlScott** [comment]
The exact same thing that happens in https://github.com/yi-editor/yi/issues/917#issuecomment-251257553. As I pointed out in https://github.com/yi-editor/yi/issues/917#issuecomment-251261541, the frontend flags don't do anything in the latest release.

**Comment by zanzix** [comment]
Yeah, that makes sense. I kind of suspected that because the installation instructions for stack did not specify the frontend, so it installed both by default. 

I honestly don't think that this has anything to do with the frontend.
Your bug should be "yi tries to install unix on windows". 

There's nothing wrong with the pango frontend support on Linux.

**Comment by RyanGlScott** [comment]
I didn't title this bug "Can't install yi on Windows" because you can't install `yi` with the `pango` frontend enabled on _any_ OS. (That implies that you can't install `yi` on Windows as an unfortunate consequence.)

And yes, there is an issue with the `pango` frontend on Linux in the sense that you can't tell `yi` to be installed with support for it (I'm not fond of the fact that one has to muck with the configuration to do this after installation, especially since the documentation claims that it should be possible to install `yi` with the `pango` frontend bundled with it).

I'm a bit exhausted discussing this, because _this used to work_. Is it possible to just revert back to the old behavior vis a vis frontend flags?

**Comment by zanzix** [comment]
> And yes, there is an issue with the pango frontend on Linux in the sense that you can't tell yi to be installed with support for it 
As I've repeated a large number of times, this conjecture is simply false. 

I can't offer you any more help because you keep insisting that something which is false is true and continue to ignore my statements to the contrary.

**Comment by noughtmare** [comment]
The documentation has not yet been updated since the recent update. So it contains incorrect information. I personally think the new update has been released too early. The reason for moving away from the command pine flags is because we wanted a more modularized Yi. Now you dont need to install pango if you don't want to use it. The problem you are encountering is probably also a consequence of this change. The way you would install Yi now is: choose one of the example configurations (we don't have a pango one yet, but I hope that wont take long) and move it to ~/.config/yi (if it is a dynamic one) (the path will probably be  %appdata%/yi on windows) and then customize and build the configuration. 

The stock Yi config was very minimal (i.e. without frontends) now it includes vty by default IIRC, but I think you are right in believing you should be able to test (preview) all the different frontends and keymaps after you just installed yi by using command line flags. I think this is still possible with the new modularized Yi, but it requires some more work.

**Comment by noughtmare** [comment]
I just made an example pango config here: #918. The installation instructions (for stack) are in the Main.hs file.

**Comment by RyanGlScott** [comment]
@noughtmare: Thanks! I appreciate the clarification.

In any case, the release of [`yi-0.13.1`](http://hackage.haskell.org/package/yi-0.13.1) has made this issue moot, as it seems to have reintroduced the `pango` and `vty` flags. (I still have installation issues, but I'll move that discussion to a [new issue](https://github.com/yi-editor/yi/issues/921).)
